# fly.toml app configuration file generated for valtown-search on 2023-08-23T15:42:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "valtown-search"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
